### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by Jurioton** [ahmad9059/dotfiles#1]
Hi, here i wanted to ask is this a post installation guide after installing hyprland in linux,and should i install everything separtely

**Comment by ahmad9059** [comment]
Bro First you have to install archilnux with minimal installation and then you have to clone this install script [repo](https://github.com/JaKooLit/Arch-Hyprland) and then just paste my dotfiles in your .config folder(remember is this repo I have so my BSPWM and grub configs also be careful if you know some racing stuff you will understand ) 
here is link of installation process https://www.youtube.com/watch?v=W2UFwkgdwNo&list=WL&index=2

**Comment by Jurioton** [comment]
Thanks brother for you kind reply
